launcher:
    windowTitle: 'Minecraft Launcher'
    browserHomeURL: 'http://mcupdate.tumblr.com/'
    loginURL: 'https://login.minecraft.net/'
    loginParameters: 'user={USERNAME}&password={PASSWORD}&version=13'
    offlineMode: false
    langs:
        - 'fr_FR'
        - 'en_US'
    debugMode: true
    autoConnectServer:
        connect: false
        address: ''
        port: ''
updater:
    askUpdateIfAvailable: true
    updateIfNewVersionAvailable: true
    customGameDir: false
    gameDir: ''
    folderName: 'minecraft'
    keyFileName: 'minecraft.key'
    loginFileEncryptionKey: 'passwordfile'
    jarList:
        - 'http://s3.amazonaws.com/MinecraftDownload/lwjgl.jar'
        - 'http://s3.amazonaws.com/MinecraftDownload/jinput.jar'
        - 'http://s3.amazonaws.com/MinecraftDownload/lwjgl_util.jar'
        - 'http://s3.amazonaws.com/MinecraftDownload/minecraft.jar'
    additionalsFiles:
        - null
    nativesList:
        windows: 'http://s3.amazonaws.com/MinecraftDownload/windows_natives.jar.lzma'
        linux: 'http://s3.amazonaws.com/MinecraftDownload/linux_natives.jar.lzma'
        macos: 'http://s3.amazonaws.com/MinecraftDownload/macosx_natives.jar.lzma'
        solaris: 'http://s3.amazonaws.com/MinecraftDownload/solaris_natives.jar.lzma'
    customVersion:
        use: false
        fileName: 'cversion'
        checkUrl: ''
        updateIfAvailable: true
gameLauncher:
    gameName: 'Minecraft'
    documentBaseURL: 'http://www.minecraft.net/game/'
    gameHost: 'www.minecraft.net'